import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const themeScript = `
(function () {
  try {
    var savedTheme = localStorage.getItem("theme");

    var allowed = {
      "dark-pro": true,
      "hits": true,
      "light": true,
      "retro-terminal": true
    };

    if (!allowed[savedTheme]) {
      savedTheme = "dark-pro";
    }

    document.documentElement.setAttribute("data-theme", savedTheme);
  } catch (e) {
    document.documentElement.setAttribute("data-theme", "dark-pro");
  }
})();
`;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <head>
        <script
          dangerouslySetInnerHTML={{ __html: themeScript }}
        />
      </head>
      <body className="min-h-full flex flex-col">
        {children}
      </body>
    </html>
  );
}
